# Generated by Django 5.2.4 on 2025-07-28 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='events',
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event'),
            preserve_default=False,
        ),
    ]
